In [1]:
# Inicializar el ambiente
import numpy as np
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn import metrics
import statsmodels.api as sm



#import math
#import random
#import time
#import os
#import sys
#from scipy.spatial import distance
#from sklearn import cluster
#from matplotlib import pyplot as plt
#%matplotlib inline
np.set_printoptions(precision=2, suppress=True) # Cortar la impresión de decimales a 1
import warnings
warnings.filterwarnings("ignore")

Cargar el archivo en formato CSV con pandas

In [2]:
df = pd.read_csv('ACC.csv')#,header=None , prefix='X') 
df.head()

x0     x1     x2     x3     x4     x5     x6     x7     x8     x9  ...  \
0  0.277 -0.010 -0.165  0.130 -0.003  0.032 -0.015  0.074 -0.157  0.183  ...   
1  0.315 -0.024 -0.163  0.134  0.004  0.072 -0.017  0.090 -0.134  0.136  ...   
2  0.450  0.013 -0.050  0.171  0.004 -0.308  0.159 -0.409 -0.039 -0.148  ...   
3  0.659  0.066  0.083  0.049  0.014 -0.213  0.028 -0.229 -0.010  0.133  ...   
4  0.653  0.085  0.096  0.060  0.015 -0.213  0.030 -0.228  0.008  0.125  ...   

    x316   x317   x318   x319   x320   x321   x322   x323   x324  class  
0 -0.054 -0.193  0.182  0.022 -0.092  0.129 -0.050 -0.055 -0.101      1  
1 -0.040 -0.194  0.199  0.020 -0.071  0.146 -0.024 -0.054 -0.071      1  
2  0.000  0.070 -0.042 -0.015 -0.082 -0.055  0.042 -0.082 -0.115      1  
3 -0.017  0.187  0.149  0.043 -0.017  0.008  0.001 -0.050 -0.090      1  
4 -0.023  0.187  0.144  0.042 -0.007  0.005  0.019 -0.057 -0.081      1  

[5 rows x 326 columns]

In [3]:
df.dtypes

x0       float64
x1       float64
x2       float64
x3       float64
x4       float64
          ...   
x321     float64
x322     float64
x323     float64
x324     float64
class      int64
Length: 326, dtype: object

In [4]:
n_neighbors = 5
num_features = df.shape[1]-1
num_class = 0
class_ = 'class'

dataset = df.values
X = dataset[:,0:num_features]#.astype(float)

#convertir clases categoricas 'string' a discretas 'entero'
clases = pd.DataFrame(df[class_].astype('category'))
clases = clases.apply(lambda x: x.cat.codes)
Y = clases.as_matrix()

In [5]:
Y[:]

array([[0],
       [0],
       [0],
       ...,
       [6],
       [6],
       [6]], dtype=int8)

### P - values 

### Modelo 

In [6]:
seed = 9
np.random.seed(seed)

# define 10-fold cross validation test harness
kfold = StratifiedKFold(n_splits=10, shuffle=True, random_state=seed)

#print(Y)


cv_real = []
cv_pred = []
for train_index, test_index in kfold.split(X, Y):

    #print("TRAIN:", train_index, "TEST:", test_index)
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = Y[train_index], Y[test_index]

    clf = RandomForestClassifier(n_estimators = 250, random_state = 42)
    clf.fit(X_train, y_train)

    # predict
    y_pred = clf.predict(X_test)
    cv_real.extend(y_test)
    cv_pred.extend(y_pred)

    #learning metrics
    #cm = confusion_matrix(y_test, y_pred)
    #print ("Confusion Matrix")
    #print (cm)

    acc = accuracy_score(y_test, y_pred)
    #print ("Accuracy score: %f" % accuracy_score(y_test, y_pred))

cm = confusion_matrix(cv_real[:], cv_pred[:])
print ("Confusion Matrix")
print (cm)
print("Var : ",np.var(cv_pred))
print ("Accuracy score: %f" % accuracy_score(cv_real, cv_pred))
print("---------------------------------------------------------------------<>\n\n\n")

Confusion Matrix
[[ 40   0   2   0   4   0   0]
 [  0 168  10   0  11   0   4]
 [  0   1 286   1  25   0   8]
 [  0   0   3  37  34   0  17]
 [  0   0   6   0 347   0  19]
 [  0   0  10   0  10  45   0]
 [  0   0   0   0  38   0 266]]
Var :  3.196374603646452
Accuracy score: 0.854167
---------------------------------------------------------------------<>



