In [7]:
# Inicializar el ambiente
import numpy as np
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn import metrics
import statsmodels.api as sm



#import math
#import random
#import time
#import os
#import sys
#from scipy.spatial import distance
#from sklearn import cluster
#from matplotlib import pyplot as plt
#%matplotlib inline
np.set_printoptions(precision=2, suppress=True) # Cortar la impresión de decimales a 1
import warnings
warnings.filterwarnings("ignore")

Cargar el archivo en formato CSV con pandas

In [8]:
df = pd.read_csv('AAC.csv')#,header=None , prefix='X') 
df.head()

X0       X1       X2       X3       X4       X5       X6       X7  \
0  6.23608  3.89755  3.11804  4.12027  5.45657  6.01336  2.44989  7.01559   
1  6.34744  3.89755  3.22940  4.12027  5.34521  6.01336  2.33853  7.12695   
2  7.50000  3.26087  4.89130  4.67391  4.13043  5.21739  2.60870  7.06522   
3  7.13624  3.05839  3.61446  6.85820  6.85820  6.20945  2.13160  7.50695   
4  7.13624  3.05839  3.52178  6.85820  6.85820  6.30213  2.03892  7.41427   

        X8        X9  ...      X11      X12      X13      X14      X15  \
0  4.67706  11.02450  ...  3.45212  5.67929  3.34076  3.45212  9.13140   
1  4.67706  11.13590  ...  3.22940  5.56793  3.45212  3.56347  9.13140   
2  2.39130  10.00000  ...  5.00000  4.13043  2.60870  5.65217  8.15217   
3  4.17053   8.89713  ...  4.54124  4.54124  4.72660  4.54124  9.08248   
4  4.17053   8.89713  ...  4.63392  4.54124  4.72660  4.54124  9.08248   

       X16      X17      X18      X19  X20  
0  6.45880  7.57238  1.78174  3.45212    1  
1  6.34744  7.46102  1.78174  3.56347    1  
2  7.06522  8.15217  1.95652  3.58696    1  
3  5.00463  5.37535  1.66821  2.59500    1  
4  5.00463  5.46803  1.66821  2.68767    1  

[5 rows x 21 columns]

In [9]:
df.dtypes

X0     float64
X1     float64
X2     float64
X3     float64
X4     float64
X5     float64
X6     float64
X7     float64
X8     float64
X9     float64
X10    float64
X11    float64
X12    float64
X13    float64
X14    float64
X15    float64
X16    float64
X17    float64
X18    float64
X19    float64
X20      int64
dtype: object

In [10]:
n_neighbors = 5
num_features = df.shape[1]-1
num_class = 0
class_ = 'X20'

dataset = df.values
X = dataset[:,0:num_features]#.astype(float)

#convertir clases categoricas 'string' a discretas 'entero'
clases = pd.DataFrame(df[class_].astype('category'))
clases = clases.apply(lambda x: x.cat.codes)
Y = clases.as_matrix()

In [14]:
Y[:]

array([[0],
       [0],
       [0],
       ...,
       [6],
       [6],
       [6]], dtype=int8)

### P - values 

### Modelo 

In [15]:
seed = 9
np.random.seed(seed)

# define 10-fold cross validation test harness
kfold = StratifiedKFold(n_splits=10, shuffle=True, random_state=seed)

#print(Y)


cv_real = []
cv_pred = []
for train_index, test_index in kfold.split(X, Y):

    #print("TRAIN:", train_index, "TEST:", test_index)
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = Y[train_index], Y[test_index]

    # runs the kNN classifier for even number of neighbors from 1 to 9


    #clf = neighbors.KNeighborsClassifier(1)
    clf = LogisticRegression()
    clf.fit(X_train, y_train)

    # predict
    y_pred = clf.predict(X_test)
    cv_real.extend(y_test)
    cv_pred.extend(y_pred)

    #learning metrics
    #cm = confusion_matrix(y_test, y_pred)
    #print ("Confusion Matrix")
    #print (cm)

    acc = accuracy_score(y_test, y_pred)
    #print ("Accuracy score: %f" % accuracy_score(y_test, y_pred))

cm = confusion_matrix(cv_real[:], cv_pred[:])
print ("Confusion Matrix")
print (cm)
print("Var : ",np.var(cv_pred))
print ("Accuracy score: %f" % accuracy_score(cv_real, cv_pred))
print("---------------------------------------------------------------------<>\n\n\n")

Confusion Matrix
[[ 34   1   3   0   2   0   6]
 [  0 186   5   0   1   0   1]
 [  2   4 281   5  22   0   7]
 [  1   3   6  43  20   1  17]
 [  1   4  26   8 247   4  82]
 [  0   0   1   0   6  52   6]
 [  2   2   8   8  81   1 202]]
Var :  3.3939919408112043
Accuracy score: 0.750718
---------------------------------------------------------------------<>



