In [7]:
# Inicializar el ambiente
import numpy as np
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn import metrics
import statsmodels.api as sm



#import math
#import random
#import time
#import os
#import sys
#from scipy.spatial import distance
#from sklearn import cluster
#from matplotlib import pyplot as plt
#%matplotlib inline
np.set_printoptions(precision=2, suppress=True) # Cortar la impresión de decimales a 1
import warnings
warnings.filterwarnings("ignore")

Cargar el archivo en formato CSV con pandas

In [8]:
df = pd.read_csv('sentencias_features.csv')#,header=None , prefix='X') 
df.head()

0  1  2  3  4  5  6  7  8  9  ...  54  55  56  57  58  59  60  61  62  \
0  0  1  0  0  0  0  0  0  0  1  ...   0   0   0   0   0   0   0   0   0   
1  0  0  0  0  0  0  0  0  0  0  ...   0   0   0   0   0   0   0   0   0   
2  0  0  0  0  0  0  0  0  0  0  ...   0   0   0   0   0   0   0   0   0   
3  0  0  0  0  0  0  0  0  0  0  ...   0   0   0   0   0   0   0   0   0   
4  0  0  0  0  0  0  0  0  0  1  ...   0   0   0   0   0   0   0   0   0   

   class  
0      0  
1      0  
2      0  
3      0  
4      0  

[5 rows x 64 columns]

In [9]:
df.dtypes

0        int64
1        int64
2        int64
3        int64
4        int64
         ...  
59       int64
60       int64
61       int64
62       int64
class    int64
Length: 64, dtype: object

In [10]:
n_neighbors = 5
num_features = df.shape[1]-1
num_class = 13
class_ = 'class'

dataset = df.values
X = dataset[:,0:num_features]#.astype(float)

#convertir clases categoricas 'string' a discretas 'entero'
clases = pd.DataFrame(df[class_].astype('category'))
clases = clases.apply(lambda x: x.cat.codes)
Y = clases.as_matrix()

In [11]:
Y[:]

array([[ 0],
       [ 0],
       [ 0],
       [ 0],
       [ 0],
       [ 0],
       [ 1],
       [ 1],
       [ 1],
       [ 2],
       [ 2],
       [ 2],
       [ 2],
       [ 2],
       [ 2],
       [ 2],
       [ 2],
       [ 2],
       [ 2],
       [ 2],
       [ 2],
       [ 2],
       [ 3],
       [ 3],
       [ 3],
       [ 4],
       [ 4],
       [ 4],
       [ 5],
       [ 5],
       [ 5],
       [ 5],
       [ 5],
       [ 5],
       [ 5],
       [ 5],
       [ 6],
       [ 6],
       [ 6],
       [ 6],
       [ 7],
       [ 7],
       [ 7],
       [ 7],
       [ 7],
       [ 8],
       [ 8],
       [ 9],
       [ 9],
       [ 9],
       [ 9],
       [ 9],
       [10],
       [10],
       [11],
       [11],
       [11],
       [11],
       [11],
       [11],
       [11],
       [11],
       [12],
       [12]], dtype=int8)

### Modelo 

In [13]:
seed = 9
np.random.seed(seed)

# define 10-fold cross validation test harness
kfold = StratifiedKFold(n_splits=10, shuffle=True, random_state=seed)

#print(Y)


cv_real = []
cv_pred = []
for train_index, test_index in kfold.split(X, Y):

    #print("TRAIN:", train_index, "TEST:", test_index)
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = Y[train_index], Y[test_index]

    clf = RandomForestClassifier(n_estimators = 250, random_state = 42)
    clf.fit(X_train, y_train)

    # predict
    y_pred = clf.predict(X_test)
    cv_real.extend(y_test)
    cv_pred.extend(y_pred)

    #learning metrics
    #cm = confusion_matrix(y_test, y_pred)
    #print ("Confusion Matrix")
    #print (cm)

    acc = accuracy_score(y_test, y_pred)
    #print ("Accuracy score: %f" % accuracy_score(y_test, y_pred))

cm = confusion_matrix(cv_real[:], cv_pred[:])
print ("Confusion Matrix")
print (cm)
print("Var : ",np.var(cv_pred))
print ("Accuracy score: %f" % accuracy_score(cv_real, cv_pred))
print("---------------------------------------------------------------------<>\n\n\n")

Confusion Matrix
[[ 2  0  4  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  3  0  0  0  0  0  0  0  0  0  0]
 [ 0  0 13  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  2  1  0  0  0  0  0  0  0  0  0]
 [ 0  0  2  0  1  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  8  0  0  0  0  0  0  0]
 [ 0  0  1  0  0  0  3  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  5  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  2  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  5  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  2  0  0]
 [ 0  0  4  0  0  0  0  0  1  0  0  3  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  2]]
Var :  10.90625
Accuracy score: 0.734375
---------------------------------------------------------------------<>



